### ISSUE TITLE
would you to implement this with Keras ?

### ISSUE THREAD

**Issue by BackT0TheFuture** [aaron-xichen/cnn-lstm-ctc#2]
Hello, Aaron

Recently I wanna do some tests about OCR, then I found your code,
I think maybe it's a good start.can you give us some data&&img samples?
BTW: Would you like to implement this with (Keras)[https://github.com/fchollet/keras] ? 

Best Regards!

**Comment by aaron-xichen** [comment]
Sounds interesting, however I am new to Keras, which means it is not an easy and fast work to make it available. Sorry the the data and image is for commercial purpose, can not be released yet.

**Comment by BackT0TheFuture** [comment]
OK, I got it , Thanks !  I'm also new to Keras, but it seems that It's hot and great !

**Comment by sinmaystar** [comment]
@goodtogood  did u run this code successfully?
