### ISSUE TITLE
Training process

### ISSUE THREAD

**Issue by zhaoluffy** [aaron-xichen/cnn-lstm-ctc#5]
When I train the model from scratch, loss : nan phenomenon is detected in the first epoch.

**Comment by aaron-xichen** [comment]
It is strange, have you changed any training parameters？

**Comment by zhaoluffy** [comment]
No, I unpack you code and get the dataset according your introduction, then I run train.sh. Finally loss:nan is display in the first epoch.

**Comment by aaron-xichen** [comment]
Do you mean after 455 iterations, loss:nan occurs? Or in the midway of training the first epoch. I just try again and no nan occurs, I have uploaded my previous training log, hope it helps.

**Comment by zhaoluffy** [comment]
Firstly, loss:nan occurs in the first step of the first epoch when I using GPU 
Secondly, just now, I training the model in CPU, then It works well.

**Comment by aaron-xichen** [comment]
What is your version of theano package, also could you please list theano configuration?

**Comment by zhaoluffy** [comment]
My theano version is  0.8.2
my theano configuration in .theanorc:
[global]
mode=FAST_RUN
device=gpu
floatX=float32
optimizer=fast_compile
[nvcc]
fastmath=True

**Comment by aaron-xichen** [comment]
Maybe you can try this
[global]
device=gpu0
floatX=float32
Btw, please remember to backup your original .theanorc

**Comment by zhaoluffy** [comment]
Thank you very much. Your theano configuration is works.

**Comment by aaron-xichen** [comment]
:)
